# Installs claude-chats so it works under whatever Ruby happens to be active.
#
# `gem install` puts the executable in the gem home of the Ruby that ran it, so
# with a version manager in play the command exists under one Ruby and not the
# next — the trap this repo's own mise.toml sets, since it pins 3.4 while the
# global Ruby may be something else. There are no dependencies to resolve here,
# so this skips gems altogether: the library is copied somewhere Ruby-agnostic
# next to a wrapper that runs it with whichever `ruby` is on PATH at the time.
# Switching Ruby versions then needs no reinstall.
#
#   make install                    # into ~/.local
#   make install PREFIX=/usr/local  # system-wide (needs sudo)
#   make reinstall                  # after a git pull
#   make uninstall
#
# rake stays the task runner for development; `make check` just forwards to it.

PREFIX  ?= $(HOME)/.local
DESTDIR ?=

NAME    := claude-chats
VERSION := $(shell sed -n "s/^ *VERSION = '\(.*\)'.*/\1/p" lib/claude_chats/version.rb)

# Staged paths, which DESTDIR may relocate for packaging...
bindir   := $(DESTDIR)$(PREFIX)/bin
sharedir := $(DESTDIR)$(PREFIX)/share/$(NAME)
target   := $(bindir)/$(NAME)
# ...and the path the wrapper will actually run from, which it may not.
runtime  := $(PREFIX)/share/$(NAME)

.DEFAULT_GOAL := help
.PHONY: help install uninstall reinstall uninstall-gem check

help:
	@echo "claude-chats $(VERSION)"
	@echo
	@echo "  make install         copy to $(PREFIX) and put $(NAME) on your PATH"
	@echo "  make reinstall       replace an existing install with this working tree"
	@echo "  make uninstall       remove it again"
	@echo "  make uninstall-gem   remove a gem-installed copy for the *active* Ruby"
	@echo "  make check           run the tests and RuboCop (via rake)"
	@echo
	@echo "  PREFIX=$(PREFIX)"

install:
	@install -d "$(sharedir)" "$(bindir)"
	@rm -rf "$(sharedir)/lib" "$(sharedir)/exe"
	@cp -R lib exe "$(sharedir)/"
	@chmod -R a+rX "$(sharedir)"
	@printf '%s\n' \
		'#!/bin/sh' \
		'# Generated by the claude-chats Makefile. Edit the repo, then reinstall.' \
		'exec ruby -I"$(runtime)/lib" "$(runtime)/exe/$(NAME)" "$$@"' > "$(target)"
	@chmod 0755 "$(target)"
	@echo "installed $(NAME) $(VERSION) -> $(target)"
	@if [ -z "$(DESTDIR)" ]; then \
		"$(target)" --version >/dev/null || { echo "but the installed command will not run"; exit 1; }; \
		found=$$(command -v $(NAME) 2>/dev/null || true); \
		if [ -z "$$found" ]; then \
			echo "note: $(PREFIX)/bin is not on your PATH, so the command is not findable yet"; \
		elif [ "$$found" != "$(target)" ]; then \
			echo "note: $$found comes earlier on your PATH and will shadow this install."; \
			echo "      If that is a gem copy, remove it with: make uninstall-gem"; \
		fi; \
	fi

uninstall:
	@rm -f "$(target)"
	@rm -rf "$(sharedir)"
	@echo "removed $(NAME) from $(PREFIX)"

reinstall:
	@$(MAKE) --no-print-directory uninstall
	@$(MAKE) --no-print-directory install

# Only touches the Ruby that is active right now; a copy under another Ruby needs
# its own run, e.g. `mise exec ruby@4.0.4 -- gem uninstall -ax claude-chats`.
uninstall-gem:
	-@gem uninstall --all --executables --ignore-dependencies $(NAME)

check:
	@bundle exec rake
